name: CI + Docker Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies & Run Tests
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pytest
          pip install -r requirements.txt
          pip install "Werkzeug<3.0"


      - name: Build Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd-app:latest
          
